name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.8, 3.9, 3.10]
    steps:
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          make lint-install
      - name: Run linter and pytest
        run: |
          make lint
